import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { bodyFont, handFont } from "../../about/fonts";
import shell from "../shell.module.css";
import { SiteHeader } from "@/components/site-header";
import { L } from "@/components/lang";
import styles from "./tangram.module.css";

/* Bilingual since 2026-09-25: every reading text is <L en zh />, the header's 中 / EN
   picks one (components/lang.tsx). Chinese: Claude's draft, for Peiwen to review. */

const root = "/assets/projects/tangram";
const sources = {
  exhibition: "Tangible Interface Show, p. 4", geometry: "Week 2, p. 7", dumbbell: "Week 3, p. 1", physical: "Week 3, p. 3", failed: "Week 3, p. 6", thickness: "Week 4, p. 4", topology: "Week 4, p. 5", options: "Week 4, p. 6", mushroom: "Week 5, p. 4", double: "Week 5, p. 2", production: "Week 6, p. 5", size: "Week 6, p. 6", board: "Week 6, p. 7", house: "Week 7, p. 4", camel: "Week 7, p. 5", butterfly: "Week 7, p. 5", tree: "Week 7, p. 6",
};
const sourcesZh = {
  exhibition: "Tangible Interface Show，第 4 页", geometry: "第 2 周，第 7 页", dumbbell: "第 3 周，第 1 页", physical: "第 3 周，第 3 页", failed: "第 3 周，第 6 页", thickness: "第 4 周，第 4 页", topology: "第 4 周，第 5 页", options: "第 4 周，第 6 页", mushroom: "第 5 周，第 4 页", double: "第 5 周，第 2 页", production: "第 6 周，第 5 页", size: "第 6 周，第 6 页", board: "第 6 周，第 7 页", house: "第 7 周，第 4 页", camel: "第 7 周，第 5 页", butterfly: "第 7 周，第 5 页", tree: "第 7 周，第 6 页",
};
function Figure({ name, width, height, alt, caption, captionZh }: { name: string; width: number; height: number; alt: string; caption: string; captionZh: string }) {
  const src = `${root}/${name}.webp`;
  return <figure className={styles.figure}><a href={src} aria-label={`Open full-size image: ${alt}`}><Image src={src} width={width} height={height} alt={alt} unoptimized={name === "final-exhibition"} sizes="(max-width: 700px) 92vw, (max-width: 1100px) 70vw, 900px" /></a><figcaption><L en={caption} zh={captionZh} /></figcaption></figure>;
}
export const metadata: Metadata = { title: "Tangram · Peiwen Zhang", description: "An independent tangible interaction and digital fabrication case study." };

export default function TangramPage() {
  return <div className={`${shell.shell} ${handFont.variable} ${bodyFont.variable} ${styles.root}`} tabIndex={-1}>
    <a className={shell.skipLink} href="#tangram-content"><L en="Skip to case study" zh="跳到项目正文" /></a>
    <SiteHeader current="projects" />
    <main id="tangram-content" className={styles.main} tabIndex={-1}>
      <Link className={styles.back} href="/projects"><L en="← Back to the attic" zh="← 回到阁楼" /></Link>
      <header className={styles.hero}><div><p className={styles.eyebrow}><L en="Tangible Interaction · Digital Fabrication · 2026" zh="实体交互 · 数字制造 · 2026" /></p><h1><L en="Tangram" zh="Tangram · 七巧板" /></h1><p className={styles.lead}><L en="Designing a modular system for fabrication and play." zh="为制作，也为游戏，设计一套模块化系统。" /></p><p><L en="A seven-week physical prototyping project that turned a traditional Tangram into a repeatable 3D-printed modular system through connector experiments, thickness testing and fabrication-scale iteration." zh="一个为期七周的实物原型项目：通过连接件实验、厚度测试和面向批量制作的迭代，把传统七巧板变成一套可以重复 3D 打印的模块化系统。" /></p><p className={styles.meta}><L en="Université Paris-Saclay · Tangible Interface / Digital Fabrication coursework · 7 weeks · Independent project" zh="巴黎-萨克雷大学 · 实体界面 / 数字制造课程 · 7 周 · 独立项目" /></p><a className={styles.logLink} href="https://the-art-of-fabricating-tangible-interfaces-2026.gitlab.dsi.universite-paris-saclay.fr/peiwen/" target="_blank" rel="noopener noreferrer"><L en="View full fabrication log ↗" zh="查看完整制作日志 ↗" /></a><a className={styles.jump} href="#constraints"><L en="Start with the constraints ↓" zh="从限制条件看起 ↓" /></a></div><Figure name="final-exhibition" width={1536} height={2048} alt="Final multicolour Tangram board at the exhibition with Peiwen Zhang project sign" caption="The final 500 × 500 mm installation at the Tangible Interface Show." captionZh="在 Tangible Interface Show 上展出的 500 × 500 mm 最终装置。" /></header>
      <section className={styles.overview}><h2><L en="At a glance" zh="项目概览" /></h2><dl className={styles.facts}><div><dt><L en="Challenge" zh="挑战" /></dt><dd><L en="Turn a traditional Tangram into a modular 3D-printed system that could connect mechanically, remain flat and scale to a 500 × 500 mm final piece." zh="把传统七巧板变成一套模块化的 3D 打印系统：能靠机械结构连接、保持平整，并能放大成一件 500 × 500 mm 的最终作品。" /></dd></div><div><dt><L en="Approach" zh="方法" /></dt><dd><L en="Iterate through geometry, tolerances, thickness, connector mechanisms and fabrication strategy using Fusion 360, PrusaSlicer and repeated physical prints." zh="借助 Fusion 360、PrusaSlicer 和一次又一次的实物打印，在几何、公差、厚度、连接机制和制作策略之间反复迭代。" /></dd></div><div><dt><L en="Output" zh="成果" /></dt><dd><L en="A 500 × 500 mm modular Tangram installation assembled from printed sets and exhibited at the Tangible Interface Show." zh="一件由多套打印件拼成的 500 × 500 mm 模块化七巧板装置，在 Tangible Interface Show 上展出。" /></dd></div></dl></section>
      <div className={styles.layout}><aside className={styles.contents}><nav aria-label="Case study chapters"><p className={styles.eyebrow}><L en="Inside the project" zh="项目目录" /></p><a href="#constraints"><L en="01 · Constraints" zh="01 · 限制条件" /></a><a href="#geometry"><L en="02 · Geometry" zh="02 · 几何" /></a><a href="#dumbbell"><L en="03 · First connector" zh="03 · 第一个连接件" /></a><a href="#thickness"><L en="04 · Thickness + topology" zh="04 · 厚度 + 拓扑" /></a><a href="#connectors"><L en="05 · Connection system" zh="05 · 连接系统" /></a><a href="#scale"><L en="06 · Scale + board" zh="06 · 尺寸 + 底板" /></a><a href="#play"><L en="07 · Exhibition + play" zh="07 · 展览 + 游戏" /></a></nav></aside><article className={styles.story}>
        <section id="constraints"><p className={styles.eyebrow}><L en="01 / Constraints" zh="01 / 限制条件" /></p><h2><L en="Design for fabrication, not only for form." zh="为制作而设计，而不只是为了形态。" /></h2><p><L en={<>The project began with a cultural reference and a manufacturing brief: make a modular, mechanically connected object without glue, then fabricate it by 3D printing. The final size was revised from the original brief to <strong>500 × 500 mm</strong>.</>} zh={<>项目从一个文化参照和一份制作要求开始：做一个模块化、靠机械结构连接、不用胶水的物件，再用 3D 打印把它做出来。最终尺寸在原始要求的基础上调整为 <strong>500 × 500 mm</strong>。</>} /></p><div className={styles.notes}><span><L en="no glue" zh="不用胶水" /></span><span><L en="press-fit connection" zh="压合连接" /></span><span><L en="3D printed" zh="3D 打印" /></span><span>500 × 500 mm</span></div></section>
        <section id="geometry"><p className={styles.eyebrow}><L en="02 / Modular geometry" zh="02 / 模块化几何" /></p><h2><L en="Reduce the puzzle to repeatable geometry." zh="把拼图简化成可以重复的几何。" /></h2><p><L en="I chose Tangram over an alternative traditional pattern direction because its seven pieces offered a culturally grounded system for modular thinking. The first challenge was translating an irregular puzzle into geometry that could be parameterized, fabricated and repeatedly connected." zh="在七巧板和另一种传统图案之间，我选了七巧板：它的七块拼板本身就是一套有文化根基的模块化思维。第一个挑战，是把一个不规则的拼图，转成可以参数化、可以制作、可以反复连接的几何。" /></p><Figure name="geometry-cad" width={2559} height={1509} alt="Fusion 360 Tangram geometry with repeated connector positions" caption={`${sources.geometry}: pieces were separated into components for fabrication.`} captionZh={`${sourcesZh.geometry}：为了制作，拼板被拆成了单独的组件。`} /></section>
        <section id="dumbbell"><p className={styles.eyebrow}><L en="03 / Connector attempt 01" zh="03 / 连接件尝试 01" /></p><h2><L en="A strong connector became a manufacturing problem." zh="一个结实的连接件，变成了制作难题。" /></h2><div className={styles.pair}><Figure name="dumbbell-cad" width={1282} height={555} alt="CAD drawing of dumbbell shaped connector" caption={`${sources.dumbbell}: 3.2 mm hole, 3.0 mm pin and 0.5 mm chamfer.`} captionZh={`${sourcesZh.dumbbell}：3.2 mm 的孔、3.0 mm 的销和 0.5 mm 的倒角。`} /><Figure name="dumbbell-physical" width={1279} height={1706} alt="Physical print test of early Tangram connector" caption={`${sources.physical}: physically strong, but not a scalable answer.`} captionZh={`${sourcesZh.physical}：实物很结实，但不是能规模化的答案。`} /></div><div className={styles.notes}><span><L en="3.2 mm hole" zh="3.2 mm 孔" /></span><span><L en="3.0 mm pin" zh="3.0 mm 销" /></span><span><L en="0.5 mm chamfer" zh="0.5 mm 倒角" /></span><span><L en="4 mm → too slow" zh="4 mm → 太慢" /></span></div><p><L en="The custom H-shaped pin made a physically strong connection. Its 3.2 mm hole, 3.0 mm pin and 0.5 mm chamfer addressed print tolerance and elephant-foot issues. But fitting that pin required pieces about 4 mm thick, and one piece took over an hour to print. It was mechanically successful, yet unsuitable for scaled fabrication." zh="定制的 H 形销连接得很牢：3.2 mm 的孔、3.0 mm 的销和 0.5 mm 的倒角，解决了打印公差和“象脚”问题。可是要装下这根销，拼板得有约 4 mm 厚，一块就要打印一个多小时。它在机械上成功了，却不适合批量制作。" /></p><div className={styles.callout}><L en="“A connector can work mechanically and still fail as a system.”" zh="“一个连接件在机械上行得通，放进系统里仍然可能失败。”" /></div><h3><L en="Print less to learn faster." zh="少打一点，学得更快。" /></h3><p><L en="I stopped reprinting the full Tangram set and tested only the two smallest triangles and two pins. I reduced the test unit so each fabrication cycle answered one question instead of reproducing the whole system, keeping a run to about 30 minutes." zh="我不再整套重打七巧板，只测试最小的两个三角形和两根销。把测试单元缩小，让每一轮制作只回答一个问题，而不是把整个系统重做一遍，每次打印控制在 30 分钟左右。" /></p><Figure name="failed-print" width={1278} height={1450} alt="Early printed Tangram triangle showing thick material and connector detail" caption={`${sources.failed}: early physical evidence from the fabrication loop.`} captionZh={`${sourcesZh.failed}：制作循环里早期的实物证据。`} /></section>
        <section id="thickness"><p className={styles.eyebrow}><L en="04 / Thickness + topology" zh="04 / 厚度 + 拓扑" /></p><h2><L en="Find the minimum thickness that still works." zh="找到仍然可用的最小厚度。" /></h2><div className={styles.thickness}><div><strong>0.2 mm</strong><span><L en="tested" zh="测试过" /></span></div><div className={styles.selected}><strong>0.4 mm</strong><span><L en="selected" zh="选定" /></span></div><div><strong>0.8 mm</strong><span><L en="tested" zh="测试过" /></span></div></div><p><L en={<>I compared 0.2 mm, 0.4 mm and 0.8 mm. <strong>0.4 mm</strong> was selected: fast enough to fabricate while remaining strong enough for this prototype. It is a selected fabrication fit, not a scientifically optimal thickness.</>} zh={<>我比较了 0.2 mm、0.4 mm 和 0.8 mm，最后选了 <strong>0.4 mm</strong>：打印够快，对这个原型来说也够结实。这是为制作挑出的合适值，并不是科学意义上的最优厚度。</>} /></p><Figure name="thickness-test" width={1280} height={1707} alt="Printed thin Tangram triangle samples on a cutting mat" caption={`${sources.thickness}: a physical thickness test.`} captionZh={`${sourcesZh.thickness}：一次实物厚度测试。`} /><h2><L en="The geometry failed before the connector did." zh="几何比连接件先出了问题。" /></h2><p><L en="The connector existed only on the two 50 mm legs; the hypotenuse had none. Back-to-back assembly exposed the consequence: the long sides could not hold the grid together. I had designed an edge locally, rather than reasoning about how every triangle participates in the larger grid." zh="连接件只在两条 50 mm 的直角边上，斜边上一个都没有。背对背拼装时，后果暴露了：长边撑不住整个网格。我只是在局部设计了一条边，却没有想清楚每个三角形在更大的网格里怎样参与连接。" /></p><Figure name="topology-failure" width={1280} height={1707} alt="Failed back to back Tangram assembly with disconnected hypotenuse edges" caption={`${sources.topology}: a full-grid problem revealed by assembly.`} captionZh={`${sourcesZh.topology}：拼装暴露出的整体网格问题。`} /></section>
        <section id="connectors"><p className={styles.eyebrow}><L en="05 / Connection system" zh="05 / 连接系统" /></p><h2><L en="Three connector ideas, tested physically." zh="三种连接思路，逐一实物测试。" /></h2><div className={styles.comparison}><div><p className={styles.tag}><L en="A · FAILED" zh="A · 失败" /></p><h3><L en="Flexible overlap" zh="柔性搭接" /></h3><p><L en="Printing heat shrank holes and made pins effectively too large; it also could not be flipped over." zh="打印时的热收缩让孔变小，销就显得太大了；而且它没法翻面。" /></p></div><div><p className={styles.tag}><L en="B · SELECTED" zh="B · 选定" /></p><h3><L en="Short mushroom" zh="短蘑菇头" /></h3><p><L en="The first bumps made insertion difficult and lifted pieces. Removing them created a flatter version that worked better." zh="最初的凸点让插入很费劲，还会把拼板顶起来。去掉凸点后，得到一个更平、更好用的版本。" /></p></div><div><p className={styles.tag}><L en="C · FAILED" zh="C · 失败" /></p><h3><L en="Tab + groove" zh="卡舌 + 凹槽" /></h3><p><L en="The tab was too thin, broke easily and slipped from the groove." zh="卡舌太薄，容易断，也容易从凹槽里滑出来。" /></p></div></div><Figure name="connector-options" width={1130} height={1141} alt="CAD comparison of three Tangram connection approaches" caption={`${sources.options}: the three concepts compared before physical testing.`} captionZh={`${sourcesZh.options}：实物测试前，三种概念的对比。`} /><div className={styles.iteration}><div><p className={styles.tag}><L en="Version 1" zh="版本 1" /></p><p><L en="Bumps were intended to help locking." zh="凸点本来是为了帮助锁紧。" /></p></div><strong aria-hidden="true">→</strong><div><p className={styles.tag}><L en="Observed" zh="观察" /></p><p><L en="Difficult insertion bent the thin triangle upward." zh="插入太费劲，把薄薄的三角形顶得向上弯。" /></p></div><strong aria-hidden="true">→</strong><div><p className={styles.tag}><L en="Version 2" zh="版本 2" /></p><p><L en="Bumps removed; the flatter connector let pieces remain flat." zh="去掉凸点；更平的连接件让拼板保持平整。" /></p></div></div><div className={styles.pair}><Figure name="short-mushroom" width={2048} height={1767} alt="Physical short mushroom connector printed on a Tangram triangle" caption={`${sources.mushroom}: the flatter revised mushroom connection.`} captionZh={`${sourcesZh.mushroom}：修改后更平的蘑菇头连接。`} /><div><h3><L en="From one anchor point to two." zh="从一个锚点，到两个。" /></h3><p><L en="One connection point allowed unwanted rotation around an edge. Adding a second anchor point constrained that movement and made the assembly more stable." zh="只有一个连接点时，拼板会绕着边转动。加上第二个锚点，就限制住了这种转动，拼装也更稳了。" /></p><div className={styles.notes}><span><L en="1 anchor → rotates" zh="1 个锚点 → 会转" /></span><span><L en="2 anchors → stable" zh="2 个锚点 → 稳定" /></span></div><Figure name="double-connection" width={742} height={401} alt="CAD comparison of Tangram pieces with connection points" caption={`${sources.double}: two anchor points replaced one.`} captionZh={`${sourcesZh.double}：两个锚点取代了一个。`} /></div></div></section>
        <section id="scale"><p className={styles.eyebrow}><L en="06 / Scale + board" zh="06 / 尺寸 + 底板" /></p><h2><L en="Designing for 144 pieces." zh="为 144 块拼板而设计。" /></h2><p><L en={<>Once the connector stopped being the main uncertainty, the design problem changed from “does one module work?” to “can I repeatedly manufacture and organize the whole system?” The plan grew to <strong>9 Tangram sets, 144 pieces</strong> and a multi-colour print workflow.</>} zh={<>当连接件不再是最大的未知数，设计问题就从“一个模块能不能用？”变成了“我能不能反复制造、并组织好整个系统？”计划扩展到 <strong>9 套七巧板、144 块拼板</strong>，以及一套多色打印流程。</>} /></p><div className={styles.notes}><span><L en="9 sets" zh="9 套" /></span><span><L en="144 pieces" zh="144 块" /></span><span><L en="6-color plan" zh="6 色方案" /></span><span><L en="4-color fallback" zh="4 色备选" /></span></div><p><L en="Six colours were planned. A four-colour approach based on the Four Color Theorem remained a fallback if filament was limited; it was not a rule that generated the final layout." zh="原本计划用六种颜色。基于四色定理的四色方案，只是耗材不够时的备选，并不是生成最终布局的规则。" /></p><div className={styles.pair}><Figure name="mass-production" width={1280} height={1707} alt="Many multicolour Tangram pieces being organised for fabrication" caption={`${sources.production}: mass-printing preparation.`} captionZh={`${sourcesZh.production}：批量打印前的准备。`} /><Figure name="size-options" width={777} height={553} alt="Diagram comparing Tangram board layout size options" caption={`${sources.size}: layout options for the 500 mm board.`} captionZh={`${sourcesZh.size}：500 mm 底板的几种布局方案。`} /></div><h2><L en="The modules worked. The board still didn’t." zh="模块成立了，底板还没有。" /></h2><div className={styles.attempts}><div><p className={styles.tag}><L en="01 · Rotate the sets" zh="01 · 旋转整套" /></p><p><L en="Exceeded the 500 × 500 mm boundary." zh="超出了 500 × 500 mm 的边界。" /></p></div><div><p className={styles.tag}><L en="02 · Complex filling" zh="02 · 复杂填充" /></p><p><L en="Too many irregular filler pieces and connector conflicts made it impractical." zh="不规则的填充块太多，连接件互相冲突，做不下去。" /></p></div><div><p className={styles.tag}><L en="03 · Border filling · selected" zh="03 · 边框填充 · 选定" /></p><p><L en="Repeated border modules filled the remaining space while preserving the central Tangram system." zh="用重复的边框模块填满剩余空间，同时保留中间的七巧板系统。" /></p></div></div><Figure name="final-board" width={1237} height={1266} alt="Final bordered 500 by 500 millimetre multicolour Tangram board" caption={`${sources.board}: final bordered composition.`} captionZh={`${sourcesZh.board}：最终带边框的构图。`} /></section>
        <section id="play"><p className={styles.eyebrow}><L en="07 / Exhibition + play" zh="07 / 展览 + 游戏" /></p><h2><L en="The final object could still become a puzzle." zh="最终的作品，依然可以变回一个拼图。" /></h2><p><L en="For the exhibition, I prepared small Tangram games: house, butterfly, camel and tree. The exhibition returned the modular system to Tangram’s original idea: a limited set of geometric parts capable of becoming many recognizable forms." zh="为了展览，我准备了几个七巧板小游戏：房子、蝴蝶、骆驼和树。展览让这套模块化系统回到了七巧板最初的想法：有限的几块几何形，可以拼出许多认得出的形状。" /></p><div className={styles.playGrid}><Figure name="play-house" width={1280} height={1707} alt="Tangram pieces arranged into a house" caption={`${sources.house}: House.`} captionZh={`${sourcesZh.house}：房子。`} /><Figure name="play-butterfly" width={1707} height={1280} alt="Tangram pieces arranged into a butterfly" caption={`${sources.butterfly}: Butterfly.`} captionZh={`${sourcesZh.butterfly}：蝴蝶。`} /><Figure name="play-camel" width={1280} height={1707} alt="Tangram pieces arranged into a camel" caption={`${sources.camel}: Camel.`} captionZh={`${sourcesZh.camel}：骆驼。`} /><Figure name="play-tree" width={1280} height={960} alt="Tangram pieces arranged into a tree" caption={`${sources.tree}: Tree.`} captionZh={`${sourcesZh.tree}：树。`} /></div><h2><L en="What fabrication changed about the design." zh="制作，改变了我对设计的理解。" /></h2><div className={styles.reflections}><div><h3><L en="Mechanical success is not manufacturing success." zh="机械上成功，不等于制作上成功。" /></h3><p><L en="The first strong connector used too much material and print time." zh="第一个结实的连接件，用料太多，打印也太久。" /></p></div><div><h3><L en="Physical iteration reveals what CAD cannot." zh="实物迭代，能发现 CAD 发现不了的问题。" /></h3><p><L en="Shrinkage, fragility, bending, rotation and topology became visible through printing and assembly." zh="收缩、易碎、弯曲、转动和拓扑问题，都是在打印和拼装中才显现出来的。" /></p></div><div><h3><L en="A module is not yet a system." zh="一个模块，还不是一个系统。" /></h3><p><L en="The final work required reasoning about edges, production, colour, board size and installation together." zh="最终的作品，要求我把边、生产、颜色、底板尺寸和安装放在一起考虑。" /></p></div></div><div className={styles.scope}><h3><L en="Prototype scope" zh="原型范围" /></h3><p><L en="This independent project documents CAD, 3D printing and physical prototyping. It did not include electronics, sensors, embedded systems, software interaction or a formal user study." zh="这个独立项目记录的是 CAD、3D 打印和实物原型。它不包含电子元件、传感器、嵌入式系统和软件交互，也没有做正式的用户研究。" /></p></div></section>
      </article></div><footer className={styles.footer}><Link href="/projects"><L en="← Back to projects" zh="← 回到项目" /></Link><a href="#tangram-content"><L en="Back to top ↑" zh="回到顶部 ↑" /></a><p><L en="Tangram · Tangible Interaction / Digital Fabrication · 2026" zh="Tangram · 实体交互 / 数字制造 · 2026" /></p></footer>
    </main></div>;
}
