import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { bodyFont, handFont } from "../../about/fonts";
import shell from "../shell.module.css";
import { SiteHeader } from "@/components/site-header";
import styles from "./tangram.module.css";

const root = "/assets/projects/tangram";
const sources = {
  exhibition: "Tangible Interface Show, p. 4", geometry: "Week 2, p. 7", dumbbell: "Week 3, p. 1", physical: "Week 3, p. 3", failed: "Week 3, p. 6", thickness: "Week 4, p. 4", topology: "Week 4, p. 5", options: "Week 4, p. 6", mushroom: "Week 5, p. 4", double: "Week 5, p. 2", production: "Week 6, p. 5", size: "Week 6, p. 6", board: "Week 6, p. 7", house: "Week 7, p. 4", camel: "Week 7, p. 5", butterfly: "Week 7, p. 5", tree: "Week 7, p. 6",
};
function Figure({ name, width, height, alt, caption }: { name: string; width: number; height: number; alt: string; caption: string }) {
  const src = `${root}/${name}.webp`;
  return <figure className={styles.figure}><a href={src} aria-label={`Open full-size image: ${alt}`}><Image src={src} width={width} height={height} alt={alt} unoptimized={name === "final-exhibition"} sizes="(max-width: 700px) 92vw, (max-width: 1100px) 70vw, 900px" /></a><figcaption>{caption}</figcaption></figure>;
}
export const metadata: Metadata = { title: "Tangram · Peiwen Zhang", description: "An independent tangible interaction and digital fabrication case study." };

export default function TangramPage() {
  return <div className={`${shell.shell} ${handFont.variable} ${bodyFont.variable} ${styles.root}`} tabIndex={-1}>
    <a className={shell.skipLink} href="#tangram-content">Skip to case study</a>
    <SiteHeader current="projects" />
    <main id="tangram-content" className={styles.main} tabIndex={-1}>
      <Link className={styles.back} href="/projects">← Back to the attic</Link>
      <header className={styles.hero}><div><p className={styles.eyebrow}>Tangible Interaction · Digital Fabrication · 2026</p><h1>Tangram</h1><p className={styles.lead}>Designing a modular system for fabrication and play.</p><p>A seven-week physical prototyping project that turned a traditional Tangram into a repeatable 3D-printed modular system through connector experiments, thickness testing and fabrication-scale iteration.</p><p className={styles.meta}>Université Paris-Saclay · Tangible Interface / Digital Fabrication coursework · 7 weeks · Independent project</p><a className={styles.logLink} href="https://the-art-of-fabricating-tangible-interfaces-2026.gitlab.dsi.universite-paris-saclay.fr/peiwen/" target="_blank" rel="noopener noreferrer">View full fabrication log ↗</a><a className={styles.jump} href="#constraints">Start with the constraints ↓</a></div><Figure name="final-exhibition" width={1536} height={2048} alt="Final multicolour Tangram board at the exhibition with Peiwen Zhang project sign" caption="The final 500 × 500 mm installation at the Tangible Interface Show." /></header>
      <section className={styles.overview}><h2>At a glance</h2><dl className={styles.facts}><div><dt>Challenge</dt><dd>Turn a traditional Tangram into a modular 3D-printed system that could connect mechanically, remain flat and scale to a 500 × 500 mm final piece.</dd></div><div><dt>Approach</dt><dd>Iterate through geometry, tolerances, thickness, connector mechanisms and fabrication strategy using Fusion 360, PrusaSlicer and repeated physical prints.</dd></div><div><dt>Output</dt><dd>A 500 × 500 mm modular Tangram installation assembled from printed sets and exhibited at the Tangible Interface Show.</dd></div></dl></section>
      <div className={styles.layout}><aside className={styles.contents}><nav aria-label="Case study chapters"><p className={styles.eyebrow}>Inside the project</p><a href="#constraints">01 · Constraints</a><a href="#geometry">02 · Geometry</a><a href="#dumbbell">03 · First connector</a><a href="#thickness">04 · Thickness + topology</a><a href="#connectors">05 · Connection system</a><a href="#scale">06 · Scale + board</a><a href="#play">07 · Exhibition + play</a></nav></aside><article className={styles.story}>
        <section id="constraints"><p className={styles.eyebrow}>01 / Constraints</p><h2>Design for fabrication, not only for form.</h2><p>The project began with a cultural reference and a manufacturing brief: make a modular, mechanically connected object without glue, then fabricate it by 3D printing. The final size was revised from the original brief to <strong>500 × 500 mm</strong>.</p><div className={styles.notes}><span>no glue</span><span>press-fit connection</span><span>3D printed</span><span>500 × 500 mm</span></div></section>
        <section id="geometry"><p className={styles.eyebrow}>02 / Modular geometry</p><h2>Reduce the puzzle to repeatable geometry.</h2><p>I chose Tangram over an alternative traditional pattern direction because its seven pieces offered a culturally grounded system for modular thinking. The first challenge was translating an irregular puzzle into geometry that could be parameterized, fabricated and repeatedly connected.</p><Figure name="geometry-cad" width={2559} height={1509} alt="Fusion 360 Tangram geometry with repeated connector positions" caption={`${sources.geometry}: pieces were separated into components for fabrication.`} /></section>
        <section id="dumbbell"><p className={styles.eyebrow}>03 / Connector attempt 01</p><h2>A strong connector became a manufacturing problem.</h2><div className={styles.pair}><Figure name="dumbbell-cad" width={1282} height={555} alt="CAD drawing of dumbbell shaped connector" caption={`${sources.dumbbell}: 3.2 mm hole, 3.0 mm pin and 0.5 mm chamfer.`} /><Figure name="dumbbell-physical" width={1279} height={1706} alt="Physical print test of early Tangram connector" caption={`${sources.physical}: physically strong, but not a scalable answer.`} /></div><div className={styles.notes}><span>3.2 mm hole</span><span>3.0 mm pin</span><span>0.5 mm chamfer</span><span>4 mm → too slow</span></div><p>The custom H-shaped pin made a physically strong connection. Its 3.2 mm hole, 3.0 mm pin and 0.5 mm chamfer addressed print tolerance and elephant-foot issues. But fitting that pin required pieces about 4 mm thick, and one piece took over an hour to print. It was mechanically successful, yet unsuitable for scaled fabrication.</p><div className={styles.callout}>“A connector can work mechanically and still fail as a system.”</div><h3>Print less to learn faster.</h3><p>I stopped reprinting the full Tangram set and tested only the two smallest triangles and two pins. I reduced the test unit so each fabrication cycle answered one question instead of reproducing the whole system, keeping a run to about 30 minutes.</p><Figure name="failed-print" width={1278} height={1450} alt="Early printed Tangram triangle showing thick material and connector detail" caption={`${sources.failed}: early physical evidence from the fabrication loop.`} /></section>
        <section id="thickness"><p className={styles.eyebrow}>04 / Thickness + topology</p><h2>Find the minimum thickness that still works.</h2><div className={styles.thickness}><div><strong>0.2 mm</strong><span>tested</span></div><div className={styles.selected}><strong>0.4 mm</strong><span>selected</span></div><div><strong>0.8 mm</strong><span>tested</span></div></div><p>I compared 0.2 mm, 0.4 mm and 0.8 mm. <strong>0.4 mm</strong> was selected: fast enough to fabricate while remaining strong enough for this prototype. It is a selected fabrication fit, not a scientifically optimal thickness.</p><Figure name="thickness-test" width={1280} height={1707} alt="Printed thin Tangram triangle samples on a cutting mat" caption={`${sources.thickness}: a physical thickness test.`} /><h2>The geometry failed before the connector did.</h2><p>The connector existed only on the two 50 mm legs; the hypotenuse had none. Back-to-back assembly exposed the consequence: the long sides could not hold the grid together. I had designed an edge locally, rather than reasoning about how every triangle participates in the larger grid.</p><Figure name="topology-failure" width={1280} height={1707} alt="Failed back to back Tangram assembly with disconnected hypotenuse edges" caption={`${sources.topology}: a full-grid problem revealed by assembly.`} /></section>
        <section id="connectors"><p className={styles.eyebrow}>05 / Connection system</p><h2>Three connector ideas, tested physically.</h2><div className={styles.comparison}><div><p className={styles.tag}>A · FAILED</p><h3>Flexible overlap</h3><p>Printing heat shrank holes and made pins effectively too large; it also could not be flipped over.</p></div><div><p className={styles.tag}>B · SELECTED</p><h3>Short mushroom</h3><p>The first bumps made insertion difficult and lifted pieces. Removing them created a flatter version that worked better.</p></div><div><p className={styles.tag}>C · FAILED</p><h3>Tab + groove</h3><p>The tab was too thin, broke easily and slipped from the groove.</p></div></div><Figure name="connector-options" width={1130} height={1141} alt="CAD comparison of three Tangram connection approaches" caption={`${sources.options}: the three concepts compared before physical testing.`} /><div className={styles.iteration}><div><p className={styles.tag}>Version 1</p><p>Bumps were intended to help locking.</p></div><strong aria-hidden="true">→</strong><div><p className={styles.tag}>Observed</p><p>Difficult insertion bent the thin triangle upward.</p></div><strong aria-hidden="true">→</strong><div><p className={styles.tag}>Version 2</p><p>Bumps removed; the flatter connector let pieces remain flat.</p></div></div><div className={styles.pair}><Figure name="short-mushroom" width={2048} height={1767} alt="Physical short mushroom connector printed on a Tangram triangle" caption={`${sources.mushroom}: the flatter revised mushroom connection.`} /><div><h3>From one anchor point to two.</h3><p>One connection point allowed unwanted rotation around an edge. Adding a second anchor point constrained that movement and made the assembly more stable.</p><div className={styles.notes}><span>1 anchor → rotates</span><span>2 anchors → stable</span></div><Figure name="double-connection" width={742} height={401} alt="CAD comparison of Tangram pieces with connection points" caption={`${sources.double}: two anchor points replaced one.`} /></div></div></section>
        <section id="scale"><p className={styles.eyebrow}>06 / Scale + board</p><h2>Designing for 144 pieces.</h2><p>Once the connector stopped being the main uncertainty, the design problem changed from “does one module work?” to “can I repeatedly manufacture and organize the whole system?” The plan grew to <strong>9 Tangram sets, 144 pieces</strong> and a multi-colour print workflow.</p><div className={styles.notes}><span>9 sets</span><span>144 pieces</span><span>6-color plan</span><span>4-color fallback</span></div><p>Six colours were planned. A four-colour approach based on the Four Color Theorem remained a fallback if filament was limited; it was not a rule that generated the final layout.</p><div className={styles.pair}><Figure name="mass-production" width={1280} height={1707} alt="Many multicolour Tangram pieces being organised for fabrication" caption={`${sources.production}: mass-printing preparation.`} /><Figure name="size-options" width={777} height={553} alt="Diagram comparing Tangram board layout size options" caption={`${sources.size}: layout options for the 500 mm board.`} /></div><h2>The modules worked. The board still didn’t.</h2><div className={styles.attempts}><div><p className={styles.tag}>01 · Rotate the sets</p><p>Exceeded the 500 × 500 mm boundary.</p></div><div><p className={styles.tag}>02 · Complex filling</p><p>Too many irregular filler pieces and connector conflicts made it impractical.</p></div><div><p className={styles.tag}>03 · Border filling · selected</p><p>Repeated border modules filled the remaining space while preserving the central Tangram system.</p></div></div><Figure name="final-board" width={1237} height={1266} alt="Final bordered 500 by 500 millimetre multicolour Tangram board" caption={`${sources.board}: final bordered composition.`} /></section>
        <section id="play"><p className={styles.eyebrow}>07 / Exhibition + play</p><h2>The final object could still become a puzzle.</h2><p>For the exhibition, I prepared small Tangram games: house, butterfly, camel and tree. The exhibition returned the modular system to Tangram’s original idea: a limited set of geometric parts capable of becoming many recognizable forms.</p><div className={styles.playGrid}><Figure name="play-house" width={1280} height={1707} alt="Tangram pieces arranged into a house" caption={`${sources.house}: House.`} /><Figure name="play-butterfly" width={1707} height={1280} alt="Tangram pieces arranged into a butterfly" caption={`${sources.butterfly}: Butterfly.`} /><Figure name="play-camel" width={1280} height={1707} alt="Tangram pieces arranged into a camel" caption={`${sources.camel}: Camel.`} /><Figure name="play-tree" width={1280} height={960} alt="Tangram pieces arranged into a tree" caption={`${sources.tree}: Tree.`} /></div><h2>What fabrication changed about the design.</h2><div className={styles.reflections}><div><h3>Mechanical success is not manufacturing success.</h3><p>The first strong connector used too much material and print time.</p></div><div><h3>Physical iteration reveals what CAD cannot.</h3><p>Shrinkage, fragility, bending, rotation and topology became visible through printing and assembly.</p></div><div><h3>A module is not yet a system.</h3><p>The final work required reasoning about edges, production, colour, board size and installation together.</p></div></div><div className={styles.scope}><h3>Prototype scope</h3><p>This independent project documents CAD, 3D printing and physical prototyping. It did not include electronics, sensors, embedded systems, software interaction or a formal user study.</p></div></section>
      </article></div><footer className={styles.footer}><Link href="/projects">← Back to projects</Link><a href="#tangram-content">Back to top ↑</a><p>Tangram · Tangible Interaction / Digital Fabrication · 2026</p></footer>
    </main></div>;
}
