import type { Metadata } from "next";
import type { ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import { bodyFont, handFont } from "../../about/fonts";
import shell from "../shell.module.css";
import { SiteHeader } from "@/components/site-header";
import { L } from "@/components/lang";
import styles from "./zoo-desk-organizer.module.css";

const root = "/assets/projects/zoo-desk-organizer";

type FigureProps = { name: string; width: number; height: number; alt: string; caption: ReactNode };
function Figure({ name, width, height, alt, caption }: FigureProps) {
  const src = `${root}/${name}.webp`;
  return <figure className={styles.figure}><a href={src} aria-label={`Open full-size image: ${alt}`}><Image src={src} width={width} height={height} alt={alt} sizes="(max-width: 700px) 92vw, (max-width: 1100px) 64vw, 820px" /></a><figcaption>{caption}</figcaption></figure>;
}

export const metadata: Metadata = { title: "ZOO Desk Organizer · Peiwen Zhang", description: "An individual product-fabrication case study by Peiwen Zhang." };

/* Bilingual since 2026-09-25: every reading text is <L en zh />, the header's 中 / EN
   picks one (components/lang.tsx). Chinese: Claude's draft, for Peiwen to review. */

export default function ZooDeskOrganizerPage() {
  return <div className={`${shell.shell} ${handFont.variable} ${bodyFont.variable} ${styles.root}`}>
    <a className={shell.skipLink} href="#zoo-content"><L en="Skip to case study" zh="跳到项目正文" /></a>
    <SiteHeader current="projects" />
    <main id="zoo-content" className={styles.main} tabIndex={-1}>
      <Link className={styles.back} href="/projects"><L en="← Back to the attic" zh="← 回到阁楼" /></Link>
      <header className={styles.hero}><div><p className={styles.eyebrow}><L en={<>Product Fabrication · CAD &amp; 3D Printing · 2026</>} zh="产品制造 · CAD 与 3D 打印 · 2026" /></p><h1><L en="ZOO Desk Organizer" zh="ZOO 桌面收纳" /></h1><p className={styles.lead}><L en="Turning everyday desk tools into one playful modular ecosystem." zh="把日常的桌面小工具，变成一个好玩的模块化小生态。" /></p><p><L en="A six-week individual CAD and 3D-printing project exploring how phone support, cable management, storage and small desk objects could share one animal-inspired product language." zh="一个为期 6 周的个人 CAD 与 3D 打印项目：探索手机支架、理线、收纳和桌上的小物件，能不能共用一套以动物为灵感的产品语言。" /></p><p className={styles.meta}><L en={<>Université Paris-Saclay · CAD &amp; 3D Printing · 6 weeks · Individual project</>} zh="巴黎-萨克雷大学 · CAD 与 3D 打印 · 6 周 · 个人项目" /></p><a className={styles.logLink} href="https://gitlab.com/u8739516597-dotcom/3dprinting-documentation-peiwenzhang/-/blob/main/README.md?ref_type=heads" target="_blank" rel="noopener noreferrer"><L en="View original project documentation ↗" zh="查看原始项目文档 ↗" /></a><a className={styles.jump} href="#motivation"><L en="Start with the motivation ↓" zh="从动机开始看 ↓" /></a></div><Figure name="final-system" width={1257} height={1322} alt="Final ZOO Desk Organizer with the elephant phone stand, storage modules and animal-inspired desk objects arranged on one tray" caption={<L en="The final ZOO system brought different desk objects into one shared setting." zh="最终的 ZOO 系统，把不同的桌面物件放进了同一个场景里。" />} /></header>
      <section className={styles.overview}><h2><L en="At a glance" zh="项目概览" /></h2><dl className={styles.facts}><div><dt><L en="Challenge" zh="挑战" /></dt><dd><L en="Make several desk tools feel like one coherent family without making every object do the same thing." zh="让几件桌面工具看起来像一家人，又不让每件都做同一件事。" /></dd></div><div><dt><L en="Approach" zh="方法" /></dt><dd><L en="Use Fusion 360 and physical print tests to explore animal silhouettes, functional geometry, fit and storage." zh="用 Fusion 360 和实物打印测试，探索动物轮廓、功能结构、配合和收纳。" /></dd></div><div><dt><L en="Output" zh="成果" /></dt><dd><L en="A desk ecosystem with phone support, cable winding, storage, a cat pot and a tray-based layout." zh="一套桌面小生态：手机支架、绕线器、收纳盒、一只猫咪小罐，再用一块底盘把它们放在一起。" /></dd></div></dl></section>
      <div className={styles.layout}><aside className={styles.contents}><nav aria-label="Case study chapters"><p className={styles.eyebrow}><L en="Inside the project" zh="项目目录" /></p><a href="#motivation"><L en="01 · Motivation" zh="01 · 动机" /></a><a href="#ecosystem"><L en="02 · Ecosystem" zh="02 · 小生态" /></a><a href="#iteration"><L en="03 · Print iteration" zh="03 · 打印迭代" /></a><a href="#function"><L en="04 · Form + function" zh="04 · 形态与功能" /></a><a href="#storage"><L en="05 · Storage" zh="05 · 收纳" /></a><a href="#final"><L en="06 · Final system" zh="06 · 最终系统" /></a></nav></aside><article className={styles.story}>
        <section id="motivation"><p className={styles.eyebrow}><L en="01 / Motivation" zh="01 / 动机" /></p><h2><L en="Make something I would actually keep using." zh="做一个我真的会一直用下去的东西。" /></h2><p><L en="This was my first substantial 3D-printing project. I wanted to learn the workflow by making something functional, aesthetically pleasing and useful enough to take home or share with friends, not an isolated classroom exercise." zh="这是我第一个像样的 3D 打印项目。我想通过做一件东西来学会整个流程——它要实用、好看，好用到可以带回家或送给朋友，而不只是一道孤立的课堂练习。" /></p><div className={styles.note}><L en="A desk organizer became the common context: a place for a phone, cables, small objects and playful forms to meet." zh="于是桌面收纳成了共同的场景：让手机、线材、小物件和好玩的造型在这里相遇。" /></div><Figure name="concept-sketch" width={1280} height={959} alt="Early hand-drawn sketch of a multi-functional desk organizer with elephant stand, fishbone cable manager, boxes and tray" caption={<L en="Early system sketch: the project began with several functions around one desk tray." zh="早期的系统草图：项目一开始就是围绕一块桌面底盘，安排好几种功能。" />} /></section>
        <section id="ecosystem"><p className={styles.eyebrow}><L en="02 / One ecosystem, many functions" zh="02 / 一个小生态，多种功能" /></p><h2><L en="Different tools, one product language." zh="不同的工具，同一种产品语言。" /></h2><p><L en="The project evolved from individual object ideas into a family of desk objects. The final group includes an elephant phone stand, fishbone cable winder, cat pot, storage boxes, base tray and a chainmail wearable experiment. They share rounded forms, animal references and a common desk context, while each object keeps a distinct role." zh="项目从一个个单独的物件想法，慢慢长成了一个桌面物件家族。最后的成员有：大象手机支架、鱼骨绕线器、猫咪小罐、收纳盒、底盘，还有一个锁子甲可穿戴实验。它们共用圆润的造型、动物的意象和同一个桌面场景，同时各自保留不同的角色。" /></p><div className={styles.family}><span><L en={<>Elephant<br /><small>phone support</small></>} zh={<>大象<br /><small>手机支架</small></>} /></span><span><L en={<>Fishbone<br /><small>cable winding</small></>} zh={<>鱼骨<br /><small>绕线</small></>} /></span><span><L en={<>Cat<br /><small>small-object storage</small></>} zh={<>猫咪<br /><small>小物收纳</small></>} /></span><span><L en={<>Boxes + tray<br /><small>organization</small></>} zh={<>收纳盒 + 底盘<br /><small>整理</small></>} /></span></div></section>
        <section id="iteration"><p className={styles.eyebrow}><L en="03 / Physical iteration" zh="03 / 实物迭代" /></p><h2><L en="The printer became part of the design process." zh="打印机也成了设计过程的一部分。" /></h2><p><L en="The early chainmail experiment looked viable in CAD, but the first small-scale bracelet fused into a rigid print: the gaps between links were not sufficient in physical fabrication. Enlarging the rings and increasing the clearance produced a flexible version." zh="早期的锁子甲实验在 CAD 里看起来没问题，可第一次打出来的小手环却粘成了硬邦邦的一块：环与环之间的间隙，到了实物里根本不够。把环放大、把间隙加宽之后，才得到了能活动的版本。" /></p><div className={styles.pair}><Figure name="chainmail-failed" width={1276} height={958} alt="Failed small chainmail bracelet print with fused links" caption={<L en="First print: visible gaps in CAD did not translate into usable clearance." zh="第一次打印：CAD 里看得见的间隙，并没有变成真正可用的间隙。" />} /><Figure name="chainmail-revised" width={960} height={1280} alt="Revised turquoise chainmail print with freely moving links" caption={<L en="Revised print: enlarged rings and gaps allowed the links to move." zh="修改后的打印：环和间隙放大后，链环终于能动了。" />} /></div><p><L en="Large flat prints raised a different constraint. The documentation records bed-adhesion failures and adjustments to bed temperature and brim use while preparing the tray." zh="大面积的平板打印又带来了另一种限制。在做底盘的过程中，文档记录了打印床附着失败，以及对热床温度和 brim 的调整。" /></p><Figure name="large-print-failure" width={1280} height={1707} alt="Failed large 3D print on a printer bed showing material buildup" caption={<L en="A large-print failure documented during the fabrication process." zh="制作过程中记录下的一次大件打印失败。" />} /></section>
        <section id="function"><p className={styles.eyebrow}><L en="04 / Form follows function" zh="04 / 形式追随功能" /></p><h2><L en="Let the animal shape do useful work." zh="让动物的造型真正派上用场。" /></h2><div className={styles.pair}><div><h3><L en="Elephant phone stand" zh="大象手机支架" /></h3><p><L en="The trunk is not decorative only: it supports a phone. I adjusted its angle in CAD to find a balance where the phone would be supported without sliding or falling backward." zh="象鼻不只是装饰，它要托住手机。我在 CAD 里反复调整它的角度，找到一个平衡点，让手机既被托住，又不会滑下来或往后倒。" /></p><Figure name="elephant-prototype" width={877} height={692} alt="Green 3D-printed elephant phone stand held in a hand" caption={<L en="A physical prototype of the elephant stand." zh="大象支架的实物原型。" />} /></div><div><h3><L en="Fishbone cable winder" zh="鱼骨绕线器" /></h3><p><L en="The fish ribs became cable-winding geometry. The recognizable silhouette mattered because its notches could also catch and organize cables." zh="鱼的肋骨变成了绕线的结构。这个一眼就能认出的轮廓很重要，因为它的凹口同时也能卡住、理顺线材。" /></p><Figure name="fishbone-cad" width={1389} height={1018} alt="CAD model of a fishbone-shaped cable winder" caption={<L en="A Fusion 360 model of the fishbone cable-winding form." zh="鱼骨绕线器的 Fusion 360 模型。" />} /></div></div><div className={styles.note}><L en="The animal metaphor became useful when a recognizable form also explained the object’s function." zh="当一个认得出的造型同时也在说明物件的用途时，动物的隐喻才真正有用。" /></div></section>
        <section id="storage"><p className={styles.eyebrow}><L en="05 / Modular fit + storage" zh="05 / 模块配合与收纳" /></p><h2><L en="Design the objects as a family." zh="把物件当成一家人来设计。" /></h2><p><L en="The storage boxes and tray moved the project from individual objects toward a desk system. I adjusted the box-to-tray relationship and lid clearance through small print tests, while the stackable boxes could be arranged around different desk needs." zh="收纳盒和底盘，让项目从一个个单独的物件走向一整套桌面系统。我通过几次小打印测试，调整盒子和底盘的关系以及盖子的间隙；可以叠放的盒子，也能按不同的桌面需要自由摆放。" /></p><div className={styles.pair}><Figure name="box-fit-cad" width={1857} height={1415} alt="CAD view of a rounded storage box lid and body showing their fit" caption={<L en="A CAD check for the lid-to-box relationship." zh="在 CAD 里检查盖子和盒身的配合。" />} /><Figure name="cat-pot" width={783} height={866} alt="Small yellow 3D-printed cat pot" caption={<L en="The cat pot added a small storage object to the shared language." zh="猫咪小罐为这套共同的语言添了一件小收纳。" />} /></div></section>
        <section id="final"><p className={styles.eyebrow}><L en="06 / Final ZOO system" zh="06 / 最终的 ZOO 系统" /></p><h2><L en="The ZOO on the desk." zh="桌上的动物园。" /></h2><p><L en="The completed system paired practical roles with a playful visual family: a tray organized the landscape, storage boxes held small objects, the elephant supported a phone, and the fishbone offered a place for cable winding. The final poster documented the intended product family rather than a production specification." zh="完成的系统把实用的角色和一个好玩的视觉家族配在了一起：底盘安排整片“地形”，收纳盒装小物件，大象托住手机，鱼骨负责绕线。最后的海报记录的是设想中的产品家族，而不是生产规格。" /></p><div className={styles.finalRow}><Figure name="final-system" width={1257} height={1322} alt="Final ZOO Desk Organizer with the elephant phone stand, storage modules and animal-inspired desk objects arranged on one tray" caption={<L en="Final assembled ZOO system." zh="组装完成的 ZOO 系统。" />} /><div className={styles.finalSupport}><div><p className={styles.tag}><L en="One visual family · multiple desk functions" zh="一个视觉家族 · 多种桌面功能" /></p><ul><li><L en="Elephant: phone support" zh="大象：手机支架" /></li><li><L en="Fishbone: cable winding" zh="鱼骨：绕线" /></li><li><L en="Cat and boxes: small-object storage" zh="猫咪和收纳盒：小物收纳" /></li><li><L en="Tray: a shared desk base" zh="底盘：共用的桌面底座" /></li></ul></div><Figure name="poster" width={817} height={578} alt="ZOO Desk Organizer final project poster with product overview drawing" caption={<L en="Final project poster, retained as supporting documentation." zh="最终的项目海报，作为辅助资料保留。" />} /></div></div><div className={styles.reflections}><div><h3><L en="Designing for print differs from designing on screen." zh="为打印而设计，和在屏幕上设计不一样。" /></h3><p><L en="Clearance, fused joints, warping and scale became meaningful through physical prints." zh="间隙、粘连的接缝、翘边和尺度，只有在实物打印里才变得真切。" /></p></div><div><h3><L en="Playful form works best when it explains use." zh="好玩的造型，最好也能说明用法。" /></h3><p><L en="The elephant and fishbone were strongest when their silhouettes supported a practical role." zh="大象和鱼骨最成功的地方，是它们的轮廓本身就承担了实际的功能。" /></p></div><div><h3><L en="A product family needs rules, not identical shapes." zh="产品家族需要的是规则，不是一模一样的形状。" /></h3><p><L en="The objects remained different while sharing a coherent visual and functional language." zh="这些物件各不相同，却共用一套连贯的视觉和功能语言。" /></p></div></div><div className={styles.scope}><h3><L en="Prototype scope" zh="原型范围" /></h3><p><L en="This individual project documents CAD, 3D printing and physical product prototyping. It did not include electronics, sensors, software interaction, a formal user study, quantified mechanical performance or production manufacturing." zh="这个个人项目记录的是 CAD、3D 打印和实物产品原型。它不涉及电子元件、传感器、软件交互、正式的用户研究、量化的力学性能，也不涉及量产制造。" /></p></div></section>
      </article></div>
      <footer className={styles.footer}><Link href="/projects"><L en="← Back to projects" zh="← 回到项目" /></Link><a href="#zoo-content"><L en="Back to top ↑" zh="回到顶部 ↑" /></a><p><L en={<>ZOO Desk Organizer · CAD &amp; 3D Printing · 2026</>} zh="ZOO 桌面收纳 · CAD 与 3D 打印 · 2026" /></p></footer>
    </main>
  </div>;
}
