import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { bodyFont, handFont } from "../../about/fonts";
import shell from "../../about/about.module.css";
import styles from "./zoo-desk-organizer.module.css";

const root = "/assets/projects/zoo-desk-organizer";

type FigureProps = { name: string; width: number; height: number; alt: string; caption: string };
function Figure({ name, width, height, alt, caption }: FigureProps) {
  const src = `${root}/${name}.webp`;
  return <figure className={styles.figure}><a href={src} aria-label={`Open full-size image: ${alt}`}><Image src={src} width={width} height={height} alt={alt} sizes="(max-width: 700px) 92vw, (max-width: 1100px) 64vw, 820px" /></a><figcaption>{caption}</figcaption></figure>;
}

export const metadata: Metadata = { title: "ZOO Desk Organizer · Peiwen Zhang", description: "An individual product-fabrication case study by Peiwen Zhang." };

export default function ZooDeskOrganizerPage() {
  return <div className={`${shell.shell} ${handFont.variable} ${bodyFont.variable} ${styles.root}`}>
    <a className={shell.skipLink} href="#zoo-content">Skip to case study</a>
    <header className={shell.header}><Link className={shell.logo} href="/" aria-label="Peiwen Zhang, Home"><span className={shell.logoName}>Peiwen Zhang</span><span className={shell.logoRole}>HCI · PRODUCT · CREATIVE TECH</span></Link><nav aria-label="Primary navigation"><Link href="/">Home</Link><Link href="/experience">Experience</Link><Link href="/projects" aria-current="location">Projects</Link><Link href="/#playground">Playground</Link><Link href="/about">About me</Link></nav></header>
    <main id="zoo-content" className={styles.main} tabIndex={-1}>
      <Link className={styles.back} href="/projects">← Back to the attic</Link>
      <header className={styles.hero}><div><p className={styles.eyebrow}>Product Fabrication · CAD &amp; 3D Printing · 2026</p><h1>ZOO Desk Organizer</h1><p className={styles.lead}>Turning everyday desk tools into one playful modular ecosystem.</p><p>A six-week individual CAD and 3D-printing project exploring how phone support, cable management, storage and small desk objects could share one animal-inspired product language.</p><p className={styles.meta}>Université Paris-Saclay · CAD &amp; 3D Printing · 6 weeks · Individual project</p><a className={styles.logLink} href="https://gitlab.com/u8739516597-dotcom/3dprinting-documentation-peiwenzhang/-/blob/main/README.md?ref_type=heads" target="_blank" rel="noopener noreferrer">View original project documentation ↗</a><a className={styles.jump} href="#motivation">Start with the motivation ↓</a></div><Figure name="final-system" width={1257} height={1322} alt="Final ZOO Desk Organizer with the elephant phone stand, storage modules and animal-inspired desk objects arranged on one tray" caption="The final ZOO system brought different desk objects into one shared setting." /></header>
      <section className={styles.overview}><h2>At a glance</h2><dl className={styles.facts}><div><dt>Challenge</dt><dd>Make several desk tools feel like one coherent family without making every object do the same thing.</dd></div><div><dt>Approach</dt><dd>Use Fusion 360 and physical print tests to explore animal silhouettes, functional geometry, fit and storage.</dd></div><div><dt>Output</dt><dd>A desk ecosystem with phone support, cable winding, storage, a cat pot and a tray-based layout.</dd></div></dl></section>
      <div className={styles.layout}><aside className={styles.contents}><nav aria-label="Case study chapters"><p className={styles.eyebrow}>Inside the project</p><a href="#motivation">01 · Motivation</a><a href="#ecosystem">02 · Ecosystem</a><a href="#iteration">03 · Print iteration</a><a href="#function">04 · Form + function</a><a href="#storage">05 · Storage</a><a href="#final">06 · Final system</a></nav></aside><article className={styles.story}>
        <section id="motivation"><p className={styles.eyebrow}>01 / Motivation</p><h2>Make something I would actually keep using.</h2><p>This was my first substantial 3D-printing project. I wanted to learn the workflow by making something functional, aesthetically pleasing and useful enough to take home or share with friends—not an isolated classroom exercise.</p><div className={styles.note}>A desk organizer became the common context: a place for a phone, cables, small objects and playful forms to meet.</div><Figure name="concept-sketch" width={1280} height={959} alt="Early hand-drawn sketch of a multi-functional desk organizer with elephant stand, fishbone cable manager, boxes and tray" caption="Early system sketch: the project began with several functions around one desk tray." /></section>
        <section id="ecosystem"><p className={styles.eyebrow}>02 / One ecosystem, many functions</p><h2>Different tools, one product language.</h2><p>The project evolved from individual object ideas into a family of desk objects. The final group includes an elephant phone stand, fishbone cable winder, cat pot, storage boxes, base tray and a chainmail wearable experiment. They share rounded forms, animal references and a common desk context, while each object keeps a distinct role.</p><div className={styles.family}><span>Elephant<br /><small>phone support</small></span><span>Fishbone<br /><small>cable winding</small></span><span>Cat<br /><small>small-object storage</small></span><span>Boxes + tray<br /><small>organization</small></span></div></section>
        <section id="iteration"><p className={styles.eyebrow}>03 / Physical iteration</p><h2>The printer became part of the design process.</h2><p>The early chainmail experiment looked viable in CAD, but the first small-scale bracelet fused into a rigid print: the gaps between links were not sufficient in physical fabrication. Enlarging the rings and increasing the clearance produced a flexible version.</p><div className={styles.pair}><Figure name="chainmail-failed" width={1276} height={958} alt="Failed small chainmail bracelet print with fused links" caption="First print: visible gaps in CAD did not translate into usable clearance." /><Figure name="chainmail-revised" width={960} height={1280} alt="Revised turquoise chainmail print with freely moving links" caption="Revised print: enlarged rings and gaps allowed the links to move." /></div><p>Large flat prints raised a different constraint. The documentation records bed-adhesion failures and adjustments to bed temperature and brim use while preparing the tray.</p><Figure name="large-print-failure" width={1280} height={1707} alt="Failed large 3D print on a printer bed showing material buildup" caption="A large-print failure documented during the fabrication process." /></section>
        <section id="function"><p className={styles.eyebrow}>04 / Form follows function</p><h2>Let the animal shape do useful work.</h2><div className={styles.pair}><div><h3>Elephant phone stand</h3><p>The trunk is not decorative only: it supports a phone. I adjusted its angle in CAD to find a balance where the phone would be supported without sliding or falling backward.</p><Figure name="elephant-prototype" width={877} height={692} alt="Green 3D-printed elephant phone stand held in a hand" caption="A physical prototype of the elephant stand." /></div><div><h3>Fishbone cable winder</h3><p>The fish ribs became cable-winding geometry. The recognizable silhouette mattered because its notches could also catch and organize cables.</p><Figure name="fishbone-cad" width={1389} height={1018} alt="CAD model of a fishbone-shaped cable winder" caption="A Fusion 360 model of the fishbone cable-winding form." /></div></div><div className={styles.note}>The animal metaphor became useful when a recognizable form also explained the object’s function.</div></section>
        <section id="storage"><p className={styles.eyebrow}>05 / Modular fit + storage</p><h2>Design the objects as a family.</h2><p>The storage boxes and tray moved the project from individual objects toward a desk system. I adjusted the box-to-tray relationship and lid clearance through small print tests, while the stackable boxes could be arranged around different desk needs.</p><div className={styles.pair}><Figure name="box-fit-cad" width={1857} height={1415} alt="CAD view of a rounded storage box lid and body showing their fit" caption="A CAD check for the lid-to-box relationship." /><Figure name="cat-pot" width={783} height={866} alt="Small yellow 3D-printed cat pot" caption="The cat pot added a small storage object to the shared language." /></div></section>
        <section id="final"><p className={styles.eyebrow}>06 / Final ZOO system</p><h2>The ZOO on the desk.</h2><p>The completed system paired practical roles with a playful visual family: a tray organized the landscape, storage boxes held small objects, the elephant supported a phone, and the fishbone offered a place for cable winding. The final poster documented the intended product family rather than a production specification.</p><div className={styles.finalRow}><Figure name="final-system" width={1257} height={1322} alt="Final ZOO Desk Organizer with the elephant phone stand, storage modules and animal-inspired desk objects arranged on one tray" caption="Final assembled ZOO system." /><div className={styles.finalSupport}><div><p className={styles.tag}>One visual family · multiple desk functions</p><ul><li>Elephant: phone support</li><li>Fishbone: cable winding</li><li>Cat and boxes: small-object storage</li><li>Tray: a shared desk base</li></ul></div><Figure name="poster" width={817} height={578} alt="ZOO Desk Organizer final project poster with product overview drawing" caption="Final project poster, retained as supporting documentation." /></div></div><div className={styles.reflections}><div><h3>Designing for print differs from designing on screen.</h3><p>Clearance, fused joints, warping and scale became meaningful through physical prints.</p></div><div><h3>Playful form works best when it explains use.</h3><p>The elephant and fishbone were strongest when their silhouettes supported a practical role.</p></div><div><h3>A product family needs rules, not identical shapes.</h3><p>The objects remained different while sharing a coherent visual and functional language.</p></div></div><div className={styles.scope}><h3>Prototype scope</h3><p>This individual project documents CAD, 3D printing and physical product prototyping. It did not include electronics, sensors, software interaction, a formal user study, quantified mechanical performance or production manufacturing.</p></div></section>
      </article></div>
      <footer className={styles.footer}><Link href="/projects">← Back to projects</Link><a href="#zoo-content">Back to top ↑</a><p>ZOO Desk Organizer · CAD &amp; 3D Printing · 2026</p></footer>
    </main>
  </div>;
}
